# Generated by Django 3.2.4 on 2022-05-23 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_image', models.FileField(blank=True, null=True, upload_to='upload')),
                ('cat_detail', models.TextField(blank=True, max_length=255, null=True)),
                ('cat_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('e_mail', models.EmailField(max_length=70)),
                ('message', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=250)),
                ('prod_detail', models.TextField(blank=True, max_length=255, null=True)),
                ('prod_price', models.FloatField(default=0)),
                ('prod_recommend', models.BooleanField(default=False)),
                ('prod_status', models.BooleanField(default=False)),
                ('prod_created', models.DateTimeField(auto_now_add=True)),
                ('prod_updated', models.DateTimeField(auto_now=True)),
                ('prod_category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_count', to='myshop.category')),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='products/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myshop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=500, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('product_comment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myshop.product')),
            ],
        ),
    ]
