# Generated by Django 3.2.4 on 2022-05-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImage',
            new_name='ImagesProduct',
        ),
        migrations.RenameField(
            model_name='imagesproduct',
            old_name='post',
            new_name='prod_id',
        ),
    ]
