# Generated by Django 3.2.4 on 2022-05-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_auto_20220523_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.FileField(blank=True, null=True, upload_to='Categories'),
        ),
        migrations.AlterField(
            model_name='imagesproduct',
            name='images',
            field=models.FileField(upload_to='Products'),
        ),
    ]
